export const itmssidebarleft = [
  { title: "New", href: "/f", icon: "/icon/star-removebg-preview.png" },
  {
    title: "random",
    href: "/random",
    icon: "/icon/random-removebg-preview.png",
  },
  {
    title: "popular",
    href: "/popular",
    icon: "/icon/fire-removebg-preview.png",
  },
  {
    title: "collection",
    href: "/collection",
    icon: "/icon/heart-removebg-preview.png",
  },
];

export const items = [
  "Pastel",
  "Vintage",
  "Retro",
  "Neon",
  "Gold",
  "Light",
  "Dark",
  "Warm",
  "Cold",
  "Summer",
  "Fall",
  "Winter",
  "Spring",
  "Happy",
  "Nature",
  "Earth",
  "Night",
  "Space",
  "Rainbow",
  "Gradient",
  "Sunset",
  "Sky",
  "Sea",
  "Kids",
  "Skin",
  "Food",
  "Cream",
  "Coffee",
  "Wedding",
  "Christmas",
  "Halloween",
];
