export const itmssidebarleft = [
  { title: "New", href: "/", icon: "/icon/star-removebg-preview.png" },
  {
    title: "random",
    href: "/random",
    icon: "/icon/random-removebg-preview.png",
  },
  {
    title: "popular",
    href: "/popular",
    icon: "/icon/fire-removebg-preview.png",
  },
  {
    title: "collection",
    href: "/collection",
    icon: "/icon/heart-removebg-preview.png",
  },
];

export const items = [
  { id: 5, name: "Vintage" },
  { id: 6, name: "Retro" },
  { id: 7, name: "Neon" },
  { id: 8, name: "Gold" },
  { id: 9, name: "Light" },
  { id: 10, name: "Dark" },
  { id: 11, name: "Warm" },
  { id: 12, name: "Cold" },
  { id: 13, name: "Summer" },
  { id: 14, name: "Fall" },
  { id: 4, name: "Pastel" },
  { id: 15, name: "Winter" },
  { id: 16, name: "Spring" },
  { id: 17, name: "Happy" },
  { id: 18, name: "Nature" },
  { id: 19, name: "Earth" },
  { id: 20, name: "Night" },
  { id: 21, name: "Space" },
  { id: 22, name: "Rainbow" },
  { id: 23, name: "Gradient" },
  { id: 24, name: "Sunset" },
  { id: 25, name: "Sky" },
  { id: 26, name: "Sea" },
  { id: 27, name: "Kids" },
  { id: 28, name: "Skin" },
  { id: 29, name: "Food" },
  { id: 30, name: "Cream" },
  { id: 31, name: "Coffee" },
  { id: 32, name: "Wedding" },
  { id: 33, name: "Christmas" },
  { id: 34, name: "Halloween" },
];

export const menuItems = [
  { label: "Palettes", href: "/" },
  { label: "Create", href: "/create" },
  { label: "Collection", href: "/collection" },
  { label: "About", href: "/about" },
  {
    label: "Instagram",
    href: "https://instagram.com/mahdi1751m",
    external: true,
  },
  { label: "Terms of Service", href: "/termsofservice" },
  { label: "Privacy Policy", href: "/privacy" },
  { label: "Git hub", href: "https://github.com/Mahdi-Devm", external: true },
];
